pr:
  - master

variables:
  - template: .devops/templates/variables.yml
  - group: 'Github and NPM secrets'

pool: Default

jobs:
  - job: BuildTestLint
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - script: |
          yarn
        displayName: yarn

      - script: |
          yarn lint
        displayName: lint
        env:
          NX_BRANCH: $(pullRequestNumber)

      - script: |
          yarn build
        displayName: build
        env:
          NX_BRANCH: $(pullRequestNumber)
