version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build
          command: yarn build
